#!/usr/bin/env python3
"""
Script to create WooCommerce Monitor application in Coolify
"""

import json
import requests
import base64

# Coolify API configuration
COOLIFY_URL = "http://187.77.26.99:8000"
API_TOKEN = "2|OyUt8feqoaBUVu1Uvvkq59CCqNjIdj4j2Vf0OXYf"
HEADERS = {
    "Authorization": f"Bearer {API_TOKEN}",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

# Application configuration
APP_CONFIG = {
    "name": "WooCommerce Monitor",
    "description": "WooCommerce error monitoring and alert system",
    "git_repository": "camster91/woo-monitor",
    "git_branch": "master",
    "build_pack": "dockerfile",  # Use Dockerfile instead of nixpacks
    "ports_exposes": "3000",
    "fqdn": "https://woo.ashbi.ca",
    "environment_id": 2,  # Same as taekwondo app
    "destination_id": 0,  # coolify destination
    "source_id": 0,
    "source_type": "App\\Models\\GithubApp",
    "health_check_enabled": True,
    "health_check_path": "/api/health",
    "health_check_port": 3000,
    "health_check_return_code": 200,
    "health_check_scheme": "http",
    "health_check_host": "localhost",
    "health_check_method": "GET",
    "health_check_interval": 5,
    "health_check_timeout": 5,
    "health_check_retries": 10,
    "health_check_start_period": 5,
    "redirect": "both",  # Redirect HTTP to HTTPS
    "limits_cpu_shares": 1024,
    "limits_cpus": "0",
    "limits_memory": "0",
    "limits_memory_reservation": "0",
    "limits_memory_swap": "0",
    "limits_memory_swappiness": 60,
    "swarm_replicas": 1,
    "compose_parsing_version": "5",
    "base_directory": "/",
    "publish_directory": None,
    "install_command": None,
    "build_command": None,
    "start_command": None,
    "post_deployment_command": None,
    "pre_deployment_command": None,
    "dockerfile_location": None,
    "dockerfile_target_build": None,
    "docker_compose_location": "/docker-compose.yaml",
    "docker_compose_raw": None,
    "docker_compose_domains": None,
    "docker_registry_image_name": None,
    "docker_registry_image_tag": None,
    "static_image": "nginx:alpine",
    "custom_docker_run_options": None,
    "custom_healthcheck_found": False,
    "custom_labels": None,  # Will be generated by Coolify
    "custom_network_aliases": None,
    "custom_nginx_configuration": "",
    "ports_mappings": None,
    "http_basic_auth_username": None,
    "http_basic_auth_password": None,
    "is_http_basic_auth_enabled": False,
    "preview_url_template": "{{pr_id}}.{{domain}}",
    "private_key_id": None,
    "repository_project_id": None,
    "git_full_url": None,
    "git_commit_sha": "HEAD",
    "watch_paths": None,
    "swarm_placement_constraints": None,
    "manual_webhook_secret_github": None,
    "manual_webhook_secret_gitlab": None,
    "manual_webhook_secret_bitbucket": None,
    "manual_webhook_secret_gitea": None,
    "additional_servers": [],
    "additional_networks_count": 0,
    "additional_servers_count": 0,
    "restart_count": 0,
    "last_restart_at": None,
    "last_restart_type": None,
    "last_online_at": None,
    "server_status": True,
    "config_hash": None,
    "deleted_at": None
}

def create_application():
    """Create the application in Coolify"""
    url = f"{COOLIFY_URL}/api/v1/applications"
    
    print(f"Creating application: {APP_CONFIG['name']}")
    print(f"Repository: {APP_CONFIG['git_repository']}")
    print(f"Domain: {APP_CONFIG['fqdn']}")
    
    # Remove None values from config
    config = {k: v for k, v in APP_CONFIG.items() if v is not None}
    
    try:
        response = requests.post(url, json=config, headers=HEADERS, timeout=30)
        print(f"Status Code: {response.status_code}")
        
        if response.status_code == 200 or response.status_code == 201:
            print("✅ Application created successfully!")
            result = response.json()
            print(f"Application UUID: {result.get('uuid', 'Unknown')}")
            print(f"Application Status: {result.get('status', 'Unknown')}")
            return result
        else:
            print(f"❌ Failed to create application: {response.status_code}")
            print(f"Response: {response.text}")
            return None
            
    except Exception as e:
        print(f"❌ Error creating application: {e}")
        return None

def check_existing_applications():
    """Check if application already exists"""
    url = f"{COOLIFY_URL}/api/v1/applications"
    
    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        if response.status_code == 200:
            apps = response.json()
            for app in apps:
                if app.get('name') == APP_CONFIG['name'] or app.get('git_repository') == APP_CONFIG['git_repository']:
                    print(f"⚠️ Application already exists: {app.get('name')} (UUID: {app.get('uuid')})")
                    return app
            print("✅ No existing application found")
            return None
        else:
            print(f"❌ Failed to get applications: {response.status_code}")
            return None
    except Exception as e:
        print(f"❌ Error checking applications: {e}")
        return None

if __name__ == "__main__":
    print("=== WooCommerce Monitor Coolify Deployment ===")
    
    # Check if application already exists
    existing = check_existing_applications()
    
    if existing:
        print(f"\nApplication already exists with UUID: {existing.get('uuid')}")
        print("If you want to recreate, delete it first.")
        choice = input("Delete and recreate? (y/N): ").strip().lower()
        if choice == 'y':
            # Delete existing application
            delete_url = f"{COOLIFY_URL}/api/v1/applications/{existing.get('uuid')}"
            delete_response = requests.delete(delete_url, headers=HEADERS)
            if delete_response.status_code == 200:
                print("✅ Application deleted. Waiting 5 seconds...")
                import time
                time.sleep(5)
                # Create new application
                create_application()
            else:
                print(f"❌ Failed to delete application: {delete_response.status_code}")
        else:
            print("Exiting without changes.")
    else:
        # Create new application
        create_application()